version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run:
          name: start #running the app
          command: npm start
      - run:
          name: test #running tests
          command: npm test
 # test:
 #   docker:
 #     - image: circleci/<language>:<version TAG>
 #   steps:
 #     - checkout
 #     - run: my-command

# Orchestrate our job run sequence
#workflows:
 # build_and_test:
  #  jobs:
   #   - build
    #  - test
